name: demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.5.3+2
  get_storage:
  lottie: ^1.4.2
  another_flushbar: ^1.10.29
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.2.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner:
  json_serializable: '>4.4.0'
  flutter_test: 
    sdk: flutter
flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"
  android: true
  ios: true
  flutter_screenutil: ^5.3.1

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/front_img.jpg
  fonts:
    - family: MIcon
      fonts:
        - asset: assets/fonts/remixicon.ttf

